name: Backend Check

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main

jobs:
  app:
    runs-on: ubuntu-latest
    
    env:
      working-directory: backend
      
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        working-directory: ${{ env.working-directory }}
        node-version: '16.x'
    - run: npm install yarn -g
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - name: Create .env
    uses: SpicyPizza/create-envfile@v1
    with:
      envkey_MONGODB_URI: ${{ secrets.SuperSecret }}
      envkey_PORT: 5000
    - run: node ./dist/index.js
