name: Backend Check

on:
  push:
    branches:
    - main
    paths:
    - ./backend/
    
  pull_request:
    branches:
    - main
    paths:
    - ./backend/

jobs:
  app:
    runs-on: ubuntu-latest
    
    env:
      working-directory: backend
      
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        working-directory: ${{ env.working-directory }}
        node-version: '16.x'
    - run: npm install yarn -g
    - run: yarn install --frozen-lockfile
    - run: yarn run test
