name: Backend Check

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main

jobs:
  app:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./backend
      
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        working-directory: ${{ env.working-directory }}
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install yarn -g
    - run: yarn install --frozen-lockfile
    - run: yarn run build
