name: Frontend Check

on:
  pull_request:
    branches:
    - main

jobs:
  app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd frontend
    - run: npm ci
    - run: npm run build
    - run: npm run build-storybook
